### ISSUE TITLE
遊戲畫面背景（湖、森林等）

### ISSUE THREAD

**Issue by Bogay** [Bogay/lady-of-the-lake#3]
如圖，主要遊戲畫面中的背景素材，目前建議這樣切分：

- [ ] 湖邊的地面
- [ ] 天空
- [ ] 樹（若干種）
- [ ] 湖面（非必要，後續可能用 shader 實現相關效果，但 fallback 是用單張圖片代替）

![圖片](https://user-images.githubusercontent.com/16890663/183961322-472974e8-160d-4097-b97b-f065334b6a45.png)

**Comment by toothpickXD** [comment]
![scene_background001](https://user-images.githubusercontent.com/100597523/184861574-bf91059d-278e-400d-a612-a9443de9eba9.png)
![scene_background002](https://user-images.githubusercontent.com/100597523/184861585-492ade12-6fef-49ea-b49c-5ef9dc2bdc83.png)
![scene_background003](https://user-images.githubusercontent.com/100597523/184861587-df3a0acd-f1a5-4253-b492-4a257df9320b.png)
![scene_background004](https://user-images.githubusercontent.com/100597523/184861592-0f23825b-3574-480e-9f29-14b671c4ebe5.png)
![scene_background005](https://user-images.githubusercontent.com/100597523/184861596-2eed8638-72d7-4e62-8ef7-d58827bb13b1.png)
